[serve.static]
plugins = ["bun-plugin-tailwind"]
env = "BUN_PUBLIC_*"

[test]
# Test patterns - Bun automatically discovers test files
testMatch = [
  "src/**/*.test.ts",
  "src/**/*.test.tsx",
  "__tests__/**/*.test.ts",
  "__tests__/**/*.test.tsx"
]

# Test environment setup
setupFilesAfterEnv = ["<rootDir>/test/setup.ts"]

# Coverage thresholds (use with --coverage flag)
[test.coverageThreshold.global]
branches = 75
functions = 80
lines = 80
statements = 80
